// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 14 Feb 2023 11:16:29 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <libmamoru_query_validator_go.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

