// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 15 Dec 2022 18:52:33 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings

/*
#cgo CFLAGS: -I${SRCDIR}/../packaged/include
#cgo LDFLAGS: -lmamoru_query_validator_go
#cgo darwin arm64 LDFLAGS: -L${SRCDIR}/../lib/darwin-arm64
#cgo linux amd64 LDFLAGS: -lm -L${SRCDIR}/../lib/linux-amd64
#include <libmamoru_query_validator_go.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// FfiChainTypeSui as declared in include/libmamoru_query_validator_go.h:29
	FfiChainTypeSui = iota
)
