// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 16 Dec 2022 15:06:42 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings

/*
#cgo CFLAGS: -I${SRCDIR}/../packaged/include
#cgo LDFLAGS: -lmamoru_query_validator_go
#cgo darwin arm64 LDFLAGS: -L${SRCDIR}/../packaged/lib/darwin-arm64
#cgo linux amd64 LDFLAGS: -Wl,--no-as-needed -ldl -lm -L${SRCDIR}/../packaged/lib/linux-amd64
#include <libmamoru_query_validator_go.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// FfiChainTypeSui as declared in include/libmamoru_query_validator_go.h:29
	FfiChainTypeSui = iota
)
