// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 15 Dec 2022 18:52:33 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings
