// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 26 Jan 2023 14:50:15 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings
