// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 16 Dec 2022 15:06:42 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings
