// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 15 Dec 2022 18:52:33 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings

/*
#cgo CFLAGS: -I${SRCDIR}/../packaged/include
#cgo LDFLAGS: -lmamoru_query_validator_go
#cgo darwin arm64 LDFLAGS: -L${SRCDIR}/../lib/darwin-arm64
#cgo linux amd64 LDFLAGS: -lm -L${SRCDIR}/../lib/linux-amd64
#include <libmamoru_query_validator_go.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// FfiValidate function as declared in include/libmamoru_query_validator_go.h:47
func FfiValidate(Chain FfiChainTypeT, Query string) FfiValidationResultT {
	cChain, cChainAllocMap := (C.FfiChainType_t)(Chain), cgoAllocsUnknown
	Query = safeString(Query)
	cQuery, cQueryAllocMap := unpackPCharString(Query)
	__ret := C.ffi_validate(cChain, cQuery)
	runtime.KeepAlive(Query)
	runtime.KeepAlive(cQueryAllocMap)
	runtime.KeepAlive(cChainAllocMap)
	__v := *NewFfiValidationResultTRef(unsafe.Pointer(&__ret))
	return __v
}

// FfiDropValidationResult function as declared in include/libmamoru_query_validator_go.h:51
func FfiDropValidationResult(Result FfiValidationResultT) {
	cResult, cResultAllocMap := Result.PassValue()
	C.ffi_drop_validation_result(cResult)
	runtime.KeepAlive(cResultAllocMap)
}
