// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 14 Feb 2023 11:16:29 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings

/*
#cgo CFLAGS: -I${SRCDIR}/../packaged/include
#cgo LDFLAGS: -lmamoru_query_validator_go
#cgo darwin,arm64 LDFLAGS: -L${SRCDIR}/../packaged/lib/darwin-arm64
#cgo darwin,amd64 LDFLAGS: -L${SRCDIR}/../packaged/lib/darwin-amd64
#cgo linux,amd64 LDFLAGS: -Wl,--no-as-needed -ldl -lm -L${SRCDIR}/../packaged/lib/linux-amd64
#include <libmamoru_query_validator_go.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// FfiValidateSql function as declared in include/libmamoru_query_validator_go.h:49
func FfiValidateSql(Chain FfiChainTypeT, Query string) FfiValidationResultT {
	cChain, cChainAllocMap := (C.FfiChainType_t)(Chain), cgoAllocsUnknown
	Query = safeString(Query)
	cQuery, cQueryAllocMap := unpackPCharString(Query)
	__ret := C.ffi_validate_sql(cChain, cQuery)
	runtime.KeepAlive(Query)
	runtime.KeepAlive(cQueryAllocMap)
	runtime.KeepAlive(cChainAllocMap)
	__v := *NewFfiValidationResultTRef(unsafe.Pointer(&__ret))
	return __v
}

// FfiValidateAssemblyScript function as declared in include/libmamoru_query_validator_go.h:80
func FfiValidateAssemblyScript(Chain FfiChainTypeT, Bytes SliceRefUint8T) FfiValidationResultT {
	cChain, cChainAllocMap := (C.FfiChainType_t)(Chain), cgoAllocsUnknown
	cBytes, cBytesAllocMap := Bytes.PassValue()
	__ret := C.ffi_validate_assembly_script(cChain, cBytes)
	runtime.KeepAlive(cBytesAllocMap)
	runtime.KeepAlive(cChainAllocMap)
	__v := *NewFfiValidationResultTRef(unsafe.Pointer(&__ret))
	return __v
}

// FfiDropValidationResult function as declared in include/libmamoru_query_validator_go.h:84
func FfiDropValidationResult(Result FfiValidationResultT) {
	cResult, cResultAllocMap := Result.PassValue()
	C.ffi_drop_validation_result(cResult)
	runtime.KeepAlive(cResultAllocMap)
}
