// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 26 Jan 2023 14:45:08 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings

/*
#cgo CFLAGS: -I${SRCDIR}/../packaged/include
#cgo LDFLAGS: -lmamoru_query_validator_go
#cgo darwin arm64 LDFLAGS: -L${SRCDIR}/../packaged/lib/darwin-arm64
#cgo darwin amd64 LDFLAGS: -L${SRCDIR}/../packaged/lib/darwin-amd64
#cgo linux amd64 LDFLAGS: -Wl,--no-as-needed -ldl -lm -L${SRCDIR}/../packaged/lib/linux-amd64
#include <libmamoru_query_validator_go.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// FfiChainTypeT type as declared in include/libmamoru_query_validator_go.h:25
type FfiChainTypeT byte

// FfiValidationResultT as declared in include/libmamoru_query_validator_go.h:47
type FfiValidationResultT struct {
	IsError        bool
	Message        *byte
	ref5dc80852    *C.FfiValidationResult_t
	allocs5dc80852 interface{}
}
